name: animatedimageslider
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.3.0
  animate_do:
  responsive_sizer: ^3.3.1
  overlapped_carousel: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  
  assets:
    - assets/
